# Generated by Django 5.0.7 on 2024-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'client'), ('engineer', 'engineer')], default='client', max_length=10),
        ),
    ]
