# Generated by Django 5.0.7 on 2024-07-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='clients_email',
        ),
    ]
