# Generated by Django 5.0.7 on 2024-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_status_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
