# Generated by Django 5.0.7 on 2024-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('active', 'active'), ('closed', 'closed')], default='open', max_length=100),
        ),
    ]
